### ISSUE TITLE
Creating a key and/or greying out targets not applicable to cities

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#13]
@brockfanning for new targets, it'd be great to have some sort of key to indicate that they are newly created for the city.  For target 5.d, I used an asterisk(*), but we'll have to indicate what that means on the site (e.g., via a key).  Also, for any National targets that are identified as N/A to local government, it'd be nice to gray them out on the site, which would also require a key notifier.  Alternatively, we can remove those that are N/A to local gov't.  Thoughts?

**Comment by brockfanning** [comment]
@dawncomer The question of the N/A indicators should be addressed first. One consideration is how this would affect the [Reporting Status](https://dawncomer.github.io/open-sdg-site-starter/reporting-status/) page. My assumption is that you'd prefer the N/A indicators *not* be counted on that page -- because if they counted, then you could never get to 100%. From a technical perspective, the easiest solution is, like you suggested, to remove the N/A indicators -- then they would disappear from the goal pages and would not be counted on the reporting status page. But if you still want them to display in some way (maybe for policy reasons) then we'll have to figure out something else.

To the question of highlighting the newly-created city indicators - one solution that occurs to me would be a new metadata field called "Tags" or something like that. That way you could give an indicator any arbitrary tags, like "New" or "Local", etc, and we'd try to figure out a nice-looking way to display them.

**Comment by dawncomer** [comment]
@brockfanning agree on not wanting them to be counted, so best to remove them all together.  I'll make those updates.  
I like tagging as 'New' or 'Local'.  I'll play around with that.  Thanks!

**Comment by brockfanning** [comment]
I've started a thread in the Open SDG repo about this: https://github.com/open-sdg/open-sdg/issues/67

**Comment by dawncomer** [comment]
Hi @brockfanning I removed the N/A Targets and indicators, but am getting errors. Let me know if I went to far with the removals.  
I removed targets 2.5, 2.b, 2.c, 4.c, 8.a, 10.5, 10.a-c, 13.a, 14.6, 17.2, 17.4 from this file: https://github.com/dawncomer/open-sdg-site-starter/blob/develop/data/translations/en/global_targets.yml

I removed indicators 2.5.1-2 and 2.c as a starting point/test before removing the rest of the indicators.  2.5.1-c was removed from https://github.com/dawncomer/open-sdg-data-starter/tree/develop/meta and https://github.com/dawncomer/open-sdg-data-starter/tree/develop/data

Here's the error
<img width="1153" alt="screen shot 2019-01-30 at 6 20 27 pm" src="https://user-images.githubusercontent.com/46500838/52026331-4913d980-24bc-11e9-9b80-62f1a9be5937.png">

Thanks!

**Comment by dawncomer** [comment]
@brockfanning here's the failed build
https://circleci.com/gh/dawncomer/open-sdg-site-starter/80

**Comment by brockfanning** [comment]
@dawncomer I'll take a look at the latest failures for you and see if anything jumps out at me.

In the meantime I wanted to let you know that I've proposed a change to the open-sdg project that should solve the problem of applying arbitrary tags. You can find more details [here](https://github.com/open-sdg/open-sdg/pull/85), and feel free to leave any feedback in that PR.

**Comment by brockfanning** [comment]
@dawncomer I did notice an issue related to an "upstream" change in Open SDG. There is an easy way to avoid these kinds of problems in the future, but for now I'd recommend merging this PR: https://github.com/dawncomer/open-sdg-site-starter/pull/17

I'm not positive it will resolve all these failures but it should help.

**Comment by dawncomer** [comment]
Thanks @brockfanning .  Still rec'd a [failure](https://circleci.com/gh/dawncomer/open-sdg-site-starter/116).  It looks like it's looking in the opensdg code for the Targets I removed, is there a way to override this and only use the targets in the local code?

**Comment by brockfanning** [comment]
I think I see what's going on - there are still a few indicators that need to be deleted from the data repository:

* 13.a.1
* 8.a.1
* 14.6.1
* 17.2.1
* 17.4.1
* 4.c.1
* 10.5.1
* 10.a.1
* 10.b.1
* 10.c.1

Because these indicators still exist in the data repository, Open SDG is linking to them from the goal pages. But they have already been removed from the site repository, so those links are pointing to non-existent pages. The automated tests fail whenever they see links to a non-existent page.

So I think the solution is to delete all of the indicators listed above from the data repository.

**Comment by dawncomer** [comment]
Thanks @brockfanning   I thought I removed from all of the repositories, so thanks for the extra set of eyes and the catch.  FYI, tonight I removed the indicators and the meta data files from the data repository...and now it has run successfully!

**Comment by dawncomer** [comment]
@brockfanning I tried to rerun the nightly job with the recent updates and rec'd a [fail for the site repository](https://circleci.com/gh/dawncomer/open-sdg-site-starter/117)
I'm not sure if this is connected, but appreciate help locating the error for the files noted

**Comment by brockfanning** [comment]
Hi @dawncomer it looks like the CircleCI nightly job didn't use the latest code, which is odd. I wonder if nightly jobs only repeat the last _successful_ build...

Anyway I just submitted an empty PR to try and trigger a normal build: https://github.com/dawncomer/open-sdg-site-starter/pull/18

Hopefully merging that PR will solve the problem - let me know how it goes!

**Comment by dawncomer** [comment]
I believe this worked!  Thanks @brockfanning 
I'll check again after the nightly build

**Comment by dawncomer** [comment]
@brockfanning following up - the updates noted above worked!  i opened a new issue on an unexpected fail that happened today, noting that it's not a result of any updates that were generated today.
