### ISSUE TITLE
Graphical data views

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#15]
Hi @Brockfanning  If we've a data set that spans 1 year, are there other visualization options beyond the current chart layout?  possibly one that allows for the x-axis to be a data point other than year? The [disaggregated data in 5-1-1](https://github.com/dawncomer/open-sdg-data-starter/blob/develop/data/indicator_5-1-1.csv) shows along one line as it's all related to the same year.  https://dawncomer.github.io/open-sdg-site-starter/5-1-1/

thoughts?

**Comment by brockfanning** [comment]
Hi @dawncomer, the graph on that indicator is actually giving me trouble - for me it's not plotting any points at all. There may be a bug here, but first some thoughts about the data set. I think what you've got here is two different units of measurement: percent employed, and percent of payroll. Here's an example of how I think it might be better structured:
```
| Year | Department Title | Sex    | Units        | Value |
|------|------------------|--------|--------------|-------|
| 2015 | Aging            | Female | % Employed   | 52.63 |
| 2015 | Aging            | Male   | % Employed   | 47.37 |
| 2015 | Aging            | Female | % of Payroll | 50.5  |
| 2015 | Aging            | Male   | % of Payroll | 49.5  |
```
I'd suggest changing to that structure, if it makes sense to you, and then we'll continue to look into the possibility of a bug.

About the single year problem, I agree with you that it probably needs something different. Personally I would try out 'bar' instead of 'line'. You can try that out by changing 'graph_type' in this file: https://github.com/dawncomer/open-sdg-data-starter/blob/develop/meta/5-1-1.md

**Comment by dawncomer** [comment]
this worked, thanks @brockfanning
