### ISSUE TITLE
Updating National Metadata Content

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#25]
Hi @Brockfanning,
I've tried to make updates to the National Metadata fields using the steps in the [README file](https://open-sdg.readthedocs.io/en/latest/making-updates/#before-you-start) but I think this is only for the Global Metadata content.   I also ran into an error "Error while loading data from github. This might be a temporary issue. Please try again later." (see image below).  Am I attempting to make these updates in the right area?  Also, how do we change the National Metadata label to 'Local Metadata'?  Thx

![image](https://user-images.githubusercontent.com/46500838/53672166-28af7a00-3c36-11e9-9f5c-0864542e5e86.png)

![image](https://user-images.githubusercontent.com/46500838/53672334-ec304e00-3c36-11e9-969d-19a44b900df7.png)

**Comment by brockfanning** [comment]
@dawncomer Not sure if this will fix it, but if you see that green icon in the lower right corner, that means you still need to "authorize" the Prose.io site. Before making changes, try clicking that green icon and following the prompts. After you "authorize" then you'll need to make your own way back to the edit page. The next time that edit page loads, you should not see the green icon in the lower right.

Give that a try and see if it maybe fixes those errors.

About switching "National" to "Local", let me give that some thought this weekend. We'd like to allow that at the Open SDG level, but if it's going to take too long then we can always override for your site.

**Comment by dawncomer** [comment]
Thanks @brockfanning It looks like I'm authorized now.  Are these edits reflected immediately, or only with the nightly build?  It looks like I'm making edits to the Global page...vs the National page.  Where do I access the National page for editing?  thanks!

**Comment by brockfanning** [comment]
@dawncomer So sorry that I didn't answer the question above sooner! All of the metadata (global or otherwise) is managed in the same file. Let me know if you're still having trouble finding a particular metadata field.

I wanted to also let you know that I've submitted a [PR in Open SDG](https://github.com/open-sdg/open-sdg/pull/121) to make it easy to change the text of the "National Metadata" tab to anything else. I'll let you know once that is merged and ready to try out.

**Comment by dawncomer** [comment]
ok thanks @brockfanning 
I'll work on updating and let you know if I meet with success.

**Comment by dawncomer** [comment]
Hi @brockfanning 
I've been able to identify the fields in prose that update the 'National' Metadata! yes, progress.  

Re: changing 'national' to 'local', was the PR accepted in Open SDG?  are we ready to try that?

thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer Yes, you're all set to try this out. [Here](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml#L97) is an example. Since your implementation doesn't need to support multiple languages, you can just put the text "Local Metadata" directly there, like so:

```
non_global_metadata: Local Metadata
```

And to clarify, this should go in the `_config.yml` file.

**Comment by dawncomer** [comment]
thanks @brockfanning I've made this update, it's working!!  👍
