### ISSUE TITLE
Coding page for non-statistical Data?

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#28]
Hi @brockfanning,
How do I set up a page like the UK has done for 8.b.1?   With a comment and link for non-statistical data?
https://sustainabledevelopment-uk.github.io/8-b-1/

![image](https://user-images.githubusercontent.com/46500838/56329336-d1a72b00-6137-11e9-99de-ae1568a040d0.png)

**Comment by brockfanning** [comment]
@dawncomer See their [metadata](https://raw.githubusercontent.com/ONSdigital/sdg-data/develop/meta/8-b-1.md) for that indicator. There are 2 key points:

1. `data_non_statistical` must be set to `true` (this prevents the graph from displaying)
2. Any amount of arbitrary text can appear after the `---` at the bottom. In their case they have:
    ```
    ---
    **Non-statistical indicator**

    We have identified the following policies relevant to this indicator: [Education and Skills Act 2008](http://www.legislation.gov.uk/ukpga/2008/25/contents).
    ````

A note about the arbitrary text: it supports [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). It also supports HTML, but Markdown is a bit easier to work with. Markdown is also good to learn about, since you can use in Github comments as well. :)

**Comment by dawncomer** [comment]
thanks @brockfanning I'll try to replicate this

**Comment by dawncomer** [comment]
this works! thanks @brockfanning 
I've used this approach for [11.4.1](https://dawncomer.github.io/open-sdg-site-starter/11-4-1/)
